version: "3"
services:
  jupyter:
    build: .
    container_name: kaggle-jupyter
    shm_size: '32gb'
    volumes:
      - ./working:/kaggle/working
      - ./input:/kaggle/input
      - /media/hiroki/birdclef-2023-dataset:/kaggle/input/birdclef-2023-dataset
    working_dir: /kaggle/working
    ports:
      - 8888:8888
    # command: jupyter lab
    #           --ip=0.0.0.0
    #           --allow-root
    #           --no-browser
    #           --collaborative
    #           --config=/kaggle/jupyter_lab_config.py
    command: jupyter lab
              --ip=0.0.0.0
              --port=8888
              --allow-root
              --no-browser
    runtime: nvidia
