version: "3"
services:
  jupyter:
    build: .
    container_name: kaggle-jupyter
    shm_size: '32gb'
    volumes:
      - ./working:/kaggle/working
      - ./input:/kaggle/input
    working_dir: /kaggle/working
    ports:
      - 8888:8888
    command: jupyter lab
              --ip=0.0.0.0
              --allow-root
              --no-browser
              --collaborative
              --config=/kaggle/jupyter_lab_config.py
    runtime: nvidia
