wandb_version: 1

BASE_PATH:
  desc: null
  value: /kaggle/input/birdclef-2023
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1683216164
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      4: 3.7.12
      5: 0.12.21
      8:
      - 1
      - 5
_wandb_kernel:
  desc: null
  value: hirokin1999
audio_augment_prob:
  desc: null
  value: 0.5
audio_len:
  desc: null
  value: 320000
augment:
  desc: null
  value: true
batch_size:
  desc: null
  value: 128
class_labels:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
  - 113
  - 114
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 127
  - 128
  - 129
  - 130
  - 131
  - 132
  - 133
  - 134
  - 135
  - 136
  - 137
  - 138
  - 139
  - 140
  - 141
  - 142
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 149
  - 150
  - 151
  - 152
  - 153
  - 154
  - 155
  - 156
  - 157
  - 158
  - 159
  - 160
  - 161
  - 162
  - 163
  - 164
  - 165
  - 166
  - 167
  - 168
  - 169
  - 170
  - 171
  - 172
  - 173
  - 174
  - 175
  - 176
  - 177
  - 178
  - 179
  - 180
  - 181
  - 182
  - 183
  - 184
  - 185
  - 186
  - 187
  - 188
  - 189
  - 190
  - 191
  - 192
  - 193
  - 194
  - 195
  - 196
  - 197
  - 198
  - 199
  - 200
  - 201
  - 202
  - 203
  - 204
  - 205
  - 206
  - 207
  - 208
  - 209
  - 210
  - 211
  - 212
  - 213
  - 214
  - 215
  - 216
  - 217
  - 218
  - 219
  - 220
  - 221
  - 222
  - 223
  - 224
  - 225
  - 226
  - 227
  - 228
  - 229
  - 230
  - 231
  - 232
  - 233
  - 234
  - 235
  - 236
  - 237
  - 238
  - 239
  - 240
  - 241
  - 242
  - 243
  - 244
  - 245
  - 246
  - 247
  - 248
  - 249
  - 250
  - 251
  - 252
  - 253
  - 254
  - 255
  - 256
  - 257
  - 258
  - 259
  - 260
  - 261
  - 262
  - 263
class_names:
  desc: null
  value:
  - abethr1
  - abhori1
  - abythr1
  - afbfly1
  - afdfly1
  - afecuc1
  - affeag1
  - afgfly1
  - afghor1
  - afmdov1
  - afpfly1
  - afpkin1
  - afpwag1
  - afrgos1
  - afrgrp1
  - afrjac1
  - afrthr1
  - amesun2
  - augbuz1
  - bagwea1
  - barswa
  - bawhor2
  - bawman1
  - bcbeat1
  - beasun2
  - bkctch1
  - bkfruw1
  - blacra1
  - blacuc1
  - blakit1
  - blaplo1
  - blbpuf2
  - blcapa2
  - blfbus1
  - blhgon1
  - blhher1
  - blksaw1
  - blnmou1
  - blnwea1
  - bltapa1
  - bltbar1
  - bltori1
  - blwlap1
  - brcale1
  - brcsta1
  - brctch1
  - brcwea1
  - brican1
  - brobab1
  - broman1
  - brosun1
  - brrwhe3
  - brtcha1
  - brubru1
  - brwwar1
  - bswdov1
  - btweye2
  - bubwar2
  - butapa1
  - cabgre1
  - carcha1
  - carwoo1
  - categr
  - ccbeat1
  - chespa1
  - chewea1
  - chibat1
  - chtapa3
  - chucis1
  - cibwar1
  - cohmar1
  - colsun2
  - combul2
  - combuz1
  - comsan
  - crefra2
  - crheag1
  - crohor1
  - darbar1
  - darter3
  - didcuc1
  - dotbar1
  - dutdov1
  - easmog1
  - eaywag1
  - edcsun3
  - egygoo
  - equaka1
  - eswdov1
  - eubeat1
  - fatrav1
  - fatwid1
  - fislov1
  - fotdro5
  - gabgos2
  - gargan
  - gbesta1
  - gnbcam2
  - gnhsun1
  - gobbun1
  - gobsta5
  - gobwea1
  - golher1
  - grbcam1
  - grccra1
  - grecor
  - greegr
  - grewoo2
  - grwpyt1
  - gryapa1
  - grywrw1
  - gybfis1
  - gycwar3
  - gyhbus1
  - gyhkin1
  - gyhneg1
  - gyhspa1
  - gytbar1
  - hadibi1
  - hamerk1
  - hartur1
  - helgui
  - hipbab1
  - hoopoe
  - huncis1
  - hunsun2
  - joygre1
  - kerspa2
  - klacuc1
  - kvbsun1
  - laudov1
  - lawgol
  - lesmaw1
  - lessts1
  - libeat1
  - litegr
  - litswi1
  - litwea1
  - loceag1
  - lotcor1
  - lotlap1
  - luebus1
  - mabeat1
  - macshr1
  - malkin1
  - marsto1
  - marsun2
  - mcptit1
  - meypar1
  - moccha1
  - mouwag1
  - ndcsun2
  - nobfly1
  - norbro1
  - norcro1
  - norfis1
  - norpuf1
  - nubwoo1
  - pabspa1
  - palfly2
  - palpri1
  - piecro1
  - piekin1
  - pitwhy
  - purgre2
  - pygbat1
  - quailf1
  - ratcis1
  - raybar1
  - rbsrob1
  - rebfir2
  - rebhor1
  - reboxp1
  - reccor
  - reccuc1
  - reedov1
  - refbar2
  - refcro1
  - reftin1
  - refwar2
  - rehblu1
  - rehwea1
  - reisee2
  - rerswa1
  - rewsta1
  - rindov
  - rocmar2
  - rostur1
  - ruegls1
  - rufcha2
  - sacibi2
  - sccsun2
  - scrcha1
  - scthon1
  - shesta1
  - sichor1
  - sincis1
  - slbgre1
  - slcbou1
  - sltnig1
  - sobfly1
  - somgre1
  - somtit4
  - soucit1
  - soufis1
  - spemou2
  - spepig1
  - spewea1
  - spfbar1
  - spfwea1
  - spmthr1
  - spwlap1
  - squher1
  - strher
  - strsee1
  - stusta1
  - subbus1
  - supsta1
  - tacsun1
  - tafpri1
  - tamdov1
  - thrnig1
  - trobou1
  - varsun2
  - vibsta2
  - vilwea1
  - vimwea1
  - walsta1
  - wbgbir1
  - wbrcha2
  - wbswea1
  - wfbeat1
  - whbcan1
  - whbcou1
  - whbcro2
  - whbtit5
  - whbwea1
  - whbwhe3
  - whcpri2
  - whctur2
  - wheslf1
  - whhsaw1
  - whihel1
  - whrshr1
  - witswa1
  - wlwwar
  - wookin1
  - woosan
  - wtbeat1
  - yebapa1
  - yebbar1
  - yebduc1
  - yebere1
  - yebgre1
  - yebsto1
  - yeccan1
  - yefcan
  - yelbis1
  - yenspu1
  - yertin1
  - yesbar1
  - yespet1
  - yetgre1
  - yewgre1
comment:
  desc: null
  value: EfficientNetB1|224x313|t=8s|lr=1e-3|act=sigmoid|secondary_label|revised|DEBUG
competition:
  desc: null
  value: birdclef-2023
cutmix_alpha:
  desc: null
  value: 0.5
cutmix_prob:
  desc: null
  value: 0.0
cv_filter:
  desc: null
  value: true
debug:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
drop_remainder:
  desc: null
  value: true
duration:
  desc: null
  value: 10
epochs:
  desc: null
  value: 30
exp_name:
  desc: null
  value: baseline
fmax:
  desc: null
  value: 16386
fmin:
  desc: null
  value: 16
fold:
  desc: null
  value: 0
freq_mask:
  desc: null
  value: 10
gn_prob:
  desc: null
  value: 0.5
hop_length:
  desc: null
  value: 1025
img_size:
  desc: null
  value:
  - 224
  - 313
in_chans:
  desc: null
  value: 1
inference_model_path:
  desc: null
  value: input/fold-0.pth
label2name:
  desc: null
  value:
    '0': abethr1
    '1': abhori1
    '10': afpfly1
    '100': gobsta5
    '101': gobwea1
    '102': golher1
    '103': grbcam1
    '104': grccra1
    '105': grecor
    '106': greegr
    '107': grewoo2
    '108': grwpyt1
    '109': gryapa1
    '11': afpkin1
    '110': grywrw1
    '111': gybfis1
    '112': gycwar3
    '113': gyhbus1
    '114': gyhkin1
    '115': gyhneg1
    '116': gyhspa1
    '117': gytbar1
    '118': hadibi1
    '119': hamerk1
    '12': afpwag1
    '120': hartur1
    '121': helgui
    '122': hipbab1
    '123': hoopoe
    '124': huncis1
    '125': hunsun2
    '126': joygre1
    '127': kerspa2
    '128': klacuc1
    '129': kvbsun1
    '13': afrgos1
    '130': laudov1
    '131': lawgol
    '132': lesmaw1
    '133': lessts1
    '134': libeat1
    '135': litegr
    '136': litswi1
    '137': litwea1
    '138': loceag1
    '139': lotcor1
    '14': afrgrp1
    '140': lotlap1
    '141': luebus1
    '142': mabeat1
    '143': macshr1
    '144': malkin1
    '145': marsto1
    '146': marsun2
    '147': mcptit1
    '148': meypar1
    '149': moccha1
    '15': afrjac1
    '150': mouwag1
    '151': ndcsun2
    '152': nobfly1
    '153': norbro1
    '154': norcro1
    '155': norfis1
    '156': norpuf1
    '157': nubwoo1
    '158': pabspa1
    '159': palfly2
    '16': afrthr1
    '160': palpri1
    '161': piecro1
    '162': piekin1
    '163': pitwhy
    '164': purgre2
    '165': pygbat1
    '166': quailf1
    '167': ratcis1
    '168': raybar1
    '169': rbsrob1
    '17': amesun2
    '170': rebfir2
    '171': rebhor1
    '172': reboxp1
    '173': reccor
    '174': reccuc1
    '175': reedov1
    '176': refbar2
    '177': refcro1
    '178': reftin1
    '179': refwar2
    '18': augbuz1
    '180': rehblu1
    '181': rehwea1
    '182': reisee2
    '183': rerswa1
    '184': rewsta1
    '185': rindov
    '186': rocmar2
    '187': rostur1
    '188': ruegls1
    '189': rufcha2
    '19': bagwea1
    '190': sacibi2
    '191': sccsun2
    '192': scrcha1
    '193': scthon1
    '194': shesta1
    '195': sichor1
    '196': sincis1
    '197': slbgre1
    '198': slcbou1
    '199': sltnig1
    '2': abythr1
    '20': barswa
    '200': sobfly1
    '201': somgre1
    '202': somtit4
    '203': soucit1
    '204': soufis1
    '205': spemou2
    '206': spepig1
    '207': spewea1
    '208': spfbar1
    '209': spfwea1
    '21': bawhor2
    '210': spmthr1
    '211': spwlap1
    '212': squher1
    '213': strher
    '214': strsee1
    '215': stusta1
    '216': subbus1
    '217': supsta1
    '218': tacsun1
    '219': tafpri1
    '22': bawman1
    '220': tamdov1
    '221': thrnig1
    '222': trobou1
    '223': varsun2
    '224': vibsta2
    '225': vilwea1
    '226': vimwea1
    '227': walsta1
    '228': wbgbir1
    '229': wbrcha2
    '23': bcbeat1
    '230': wbswea1
    '231': wfbeat1
    '232': whbcan1
    '233': whbcou1
    '234': whbcro2
    '235': whbtit5
    '236': whbwea1
    '237': whbwhe3
    '238': whcpri2
    '239': whctur2
    '24': beasun2
    '240': wheslf1
    '241': whhsaw1
    '242': whihel1
    '243': whrshr1
    '244': witswa1
    '245': wlwwar
    '246': wookin1
    '247': woosan
    '248': wtbeat1
    '249': yebapa1
    '25': bkctch1
    '250': yebbar1
    '251': yebduc1
    '252': yebere1
    '253': yebgre1
    '254': yebsto1
    '255': yeccan1
    '256': yefcan
    '257': yelbis1
    '258': yenspu1
    '259': yertin1
    '26': bkfruw1
    '260': yesbar1
    '261': yespet1
    '262': yetgre1
    '263': yewgre1
    '27': blacra1
    '28': blacuc1
    '29': blakit1
    '3': afbfly1
    '30': blaplo1
    '31': blbpuf2
    '32': blcapa2
    '33': blfbus1
    '34': blhgon1
    '35': blhher1
    '36': blksaw1
    '37': blnmou1
    '38': blnwea1
    '39': bltapa1
    '4': afdfly1
    '40': bltbar1
    '41': bltori1
    '42': blwlap1
    '43': brcale1
    '44': brcsta1
    '45': brctch1
    '46': brcwea1
    '47': brican1
    '48': brobab1
    '49': broman1
    '5': afecuc1
    '50': brosun1
    '51': brrwhe3
    '52': brtcha1
    '53': brubru1
    '54': brwwar1
    '55': bswdov1
    '56': btweye2
    '57': bubwar2
    '58': butapa1
    '59': cabgre1
    '6': affeag1
    '60': carcha1
    '61': carwoo1
    '62': categr
    '63': ccbeat1
    '64': chespa1
    '65': chewea1
    '66': chibat1
    '67': chtapa3
    '68': chucis1
    '69': cibwar1
    '7': afgfly1
    '70': cohmar1
    '71': colsun2
    '72': combul2
    '73': combuz1
    '74': comsan
    '75': crefra2
    '76': crheag1
    '77': crohor1
    '78': darbar1
    '79': darter3
    '8': afghor1
    '80': didcuc1
    '81': dotbar1
    '82': dutdov1
    '83': easmog1
    '84': eaywag1
    '85': edcsun3
    '86': egygoo
    '87': equaka1
    '88': eswdov1
    '89': eubeat1
    '9': afmdov1
    '90': fatrav1
    '91': fatwid1
    '92': fislov1
    '93': fotdro5
    '94': gabgos2
    '95': gargan
    '96': gbesta1
    '97': gnbcam2
    '98': gnhsun1
    '99': gobbun1
label_smoothing:
  desc: null
  value: 0.05
loss:
  desc: null
  value: CCE
lr:
  desc: null
  value: 0.001
lr_min:
  desc: null
  value: 1.0e-05
mask_prob:
  desc: null
  value: 0.5
mixup_alpha:
  desc: null
  value: 0.5
mixup_prob:
  desc: null
  value: 0.65
model_name:
  desc: null
  value: tf_efficientnet_b1_ns
monitor:
  desc: null
  value: auc
n_fft:
  desc: null
  value: 2028
n_mels:
  desc: null
  value: 224
name2label:
  desc: null
  value:
    abethr1: 0
    abhori1: 1
    abythr1: 2
    afbfly1: 3
    afdfly1: 4
    afecuc1: 5
    affeag1: 6
    afgfly1: 7
    afghor1: 8
    afmdov1: 9
    afpfly1: 10
    afpkin1: 11
    afpwag1: 12
    afrgos1: 13
    afrgrp1: 14
    afrjac1: 15
    afrthr1: 16
    amesun2: 17
    augbuz1: 18
    bagwea1: 19
    barswa: 20
    bawhor2: 21
    bawman1: 22
    bcbeat1: 23
    beasun2: 24
    bkctch1: 25
    bkfruw1: 26
    blacra1: 27
    blacuc1: 28
    blakit1: 29
    blaplo1: 30
    blbpuf2: 31
    blcapa2: 32
    blfbus1: 33
    blhgon1: 34
    blhher1: 35
    blksaw1: 36
    blnmou1: 37
    blnwea1: 38
    bltapa1: 39
    bltbar1: 40
    bltori1: 41
    blwlap1: 42
    brcale1: 43
    brcsta1: 44
    brctch1: 45
    brcwea1: 46
    brican1: 47
    brobab1: 48
    broman1: 49
    brosun1: 50
    brrwhe3: 51
    brtcha1: 52
    brubru1: 53
    brwwar1: 54
    bswdov1: 55
    btweye2: 56
    bubwar2: 57
    butapa1: 58
    cabgre1: 59
    carcha1: 60
    carwoo1: 61
    categr: 62
    ccbeat1: 63
    chespa1: 64
    chewea1: 65
    chibat1: 66
    chtapa3: 67
    chucis1: 68
    cibwar1: 69
    cohmar1: 70
    colsun2: 71
    combul2: 72
    combuz1: 73
    comsan: 74
    crefra2: 75
    crheag1: 76
    crohor1: 77
    darbar1: 78
    darter3: 79
    didcuc1: 80
    dotbar1: 81
    dutdov1: 82
    easmog1: 83
    eaywag1: 84
    edcsun3: 85
    egygoo: 86
    equaka1: 87
    eswdov1: 88
    eubeat1: 89
    fatrav1: 90
    fatwid1: 91
    fislov1: 92
    fotdro5: 93
    gabgos2: 94
    gargan: 95
    gbesta1: 96
    gnbcam2: 97
    gnhsun1: 98
    gobbun1: 99
    gobsta5: 100
    gobwea1: 101
    golher1: 102
    grbcam1: 103
    grccra1: 104
    grecor: 105
    greegr: 106
    grewoo2: 107
    grwpyt1: 108
    gryapa1: 109
    grywrw1: 110
    gybfis1: 111
    gycwar3: 112
    gyhbus1: 113
    gyhkin1: 114
    gyhneg1: 115
    gyhspa1: 116
    gytbar1: 117
    hadibi1: 118
    hamerk1: 119
    hartur1: 120
    helgui: 121
    hipbab1: 122
    hoopoe: 123
    huncis1: 124
    hunsun2: 125
    joygre1: 126
    kerspa2: 127
    klacuc1: 128
    kvbsun1: 129
    laudov1: 130
    lawgol: 131
    lesmaw1: 132
    lessts1: 133
    libeat1: 134
    litegr: 135
    litswi1: 136
    litwea1: 137
    loceag1: 138
    lotcor1: 139
    lotlap1: 140
    luebus1: 141
    mabeat1: 142
    macshr1: 143
    malkin1: 144
    marsto1: 145
    marsun2: 146
    mcptit1: 147
    meypar1: 148
    moccha1: 149
    mouwag1: 150
    ndcsun2: 151
    nobfly1: 152
    norbro1: 153
    norcro1: 154
    norfis1: 155
    norpuf1: 156
    nubwoo1: 157
    pabspa1: 158
    palfly2: 159
    palpri1: 160
    piecro1: 161
    piekin1: 162
    pitwhy: 163
    purgre2: 164
    pygbat1: 165
    quailf1: 166
    ratcis1: 167
    raybar1: 168
    rbsrob1: 169
    rebfir2: 170
    rebhor1: 171
    reboxp1: 172
    reccor: 173
    reccuc1: 174
    reedov1: 175
    refbar2: 176
    refcro1: 177
    reftin1: 178
    refwar2: 179
    rehblu1: 180
    rehwea1: 181
    reisee2: 182
    rerswa1: 183
    rewsta1: 184
    rindov: 185
    rocmar2: 186
    rostur1: 187
    ruegls1: 188
    rufcha2: 189
    sacibi2: 190
    sccsun2: 191
    scrcha1: 192
    scthon1: 193
    shesta1: 194
    sichor1: 195
    sincis1: 196
    slbgre1: 197
    slcbou1: 198
    sltnig1: 199
    sobfly1: 200
    somgre1: 201
    somtit4: 202
    soucit1: 203
    soufis1: 204
    spemou2: 205
    spepig1: 206
    spewea1: 207
    spfbar1: 208
    spfwea1: 209
    spmthr1: 210
    spwlap1: 211
    squher1: 212
    strher: 213
    strsee1: 214
    stusta1: 215
    subbus1: 216
    supsta1: 217
    tacsun1: 218
    tafpri1: 219
    tamdov1: 220
    thrnig1: 221
    trobou1: 222
    varsun2: 223
    vibsta2: 224
    vilwea1: 225
    vimwea1: 226
    walsta1: 227
    wbgbir1: 228
    wbrcha2: 229
    wbswea1: 230
    wfbeat1: 231
    whbcan1: 232
    whbcou1: 233
    whbcro2: 234
    whbtit5: 235
    whbwea1: 236
    whbwhe3: 237
    whcpri2: 238
    whctur2: 239
    wheslf1: 240
    whhsaw1: 241
    whihel1: 242
    whrshr1: 243
    witswa1: 244
    wlwwar: 245
    wookin1: 246
    woosan: 247
    wtbeat1: 248
    yebapa1: 249
    yebbar1: 250
    yebduc1: 251
    yebere1: 252
    yebgre1: 253
    yebsto1: 254
    yeccan1: 255
    yefcan: 256
    yelbis1: 257
    yenspu1: 258
    yertin1: 259
    yesbar1: 260
    yespet1: 261
    yetgre1: 262
    yewgre1: 263
normalize:
  desc: null
  value: true
notebook_link:
  desc: null
  value: https://www.kaggle.com/awsaf49/birdclef23-effnet-fsr-cutmixup-train/edit
num_classes:
  desc: null
  value: 264
num_fold:
  desc: null
  value: 5
optimizer:
  desc: null
  value: Adam
pretrain:
  desc: null
  value: true
pretrained_model_path:
  desc: null
  value: /kaggle/working/pre-training/exp1_pre_attblock_fold-0_20230501_pretrained.pth
sample_rate:
  desc: null
  value: 32000
scheduler:
  desc: null
  value: cos
seed:
  desc: null
  value: 42
selected_folds:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
spec_augment_prob:
  desc: null
  value: 0.8
tab_cols:
  desc: null
  value:
  - filename
target_col:
  desc: null
  value:
  - target
test_bs:
  desc: null
  value: 2
test_duration:
  desc: null
  value: 5
time_mask:
  desc: null
  value: 20
timeshift_prob:
  desc: null
  value: 0.0
top_db:
  desc: null
  value: 80
training_plot:
  desc: null
  value: true
tta:
  desc: null
  value: 1
upsample_thr:
  desc: null
  value: 50
valid_bs:
  desc: null
  value: 128
verbose:
  desc: null
  value: 0
wandb:
  desc: null
  value: true
warmup_lr_init:
  desc: null
  value: 5.0e-05
warmup_t:
  desc: null
  value: 5
